# Dependabot configuration for automated dependency updates
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  # Monitor GitHub Actions workflow dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "chore"
      include: "scope"
      
  # Monitor Swift Package Manager dependencies
  # Note: Currently no external dependencies, but will monitor Package.swift changes
  - package-ecosystem: "swift"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "swift"
    commit-message:
      prefix: "chore"
      include: "scope"
