# SwiftLint Configuration for Ephemeris

# Paths to include/exclude from linting
included:
  - Ephemeris
  - EphemerisTests

excluded:
  - Pods
  - .build
  - DerivedData
  - fastlane
  - documentation

# Disabled rules (relaxed for existing codebase)
disabled_rules:
  - trailing_whitespace # Allow trailing whitespace for now
  - line_length # Disable line length checks for long documentation URLs
  - function_body_length # Some complex calculations need more lines
  - type_body_length # Allow larger types for now
  - cyclomatic_complexity # Allow complex orbital calculations

# Opt-in rules
opt_in_rules:
  - empty_count
  - empty_string

# Rule configurations
file_length:
  warning: 600
  error: 1200

# Naming conventions
identifier_name:
  min_length:
    warning: 1
    error: 0
  max_length:
    warning: 60
    error: 80
  excluded:
    - id
    - i
    - j
    - k
    - x
    - y
    - z
    - a
    - e
    - v
    - M
    - E
    - u
    - f
    - n
    - r

# Force try should be allowed in tests
force_try:
  severity: warning

# Allow force unwrapping in test code
force_unwrapping:
  severity: warning

# Type name configuration
type_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 60
    error: 80

# Reporting
reporter: "xcode"
