# SwiftLint Configuration for Ephemeris

# Paths to include/exclude from linting
included:
  - Ephemeris
  - EphemerisTests
  - EphemerisDemo

excluded:
  - Pods
  - .build
  - DerivedData
  - fastlane
  - documentation

# Disabled rules
disabled_rules:
  - trailing_whitespace # Allow trailing whitespace for now

# Opt-in rules
opt_in_rules:
  - empty_count
  - empty_string

# Rule configurations
line_length:
  warning: 120
  error: 150
  ignores_comments: true
  ignores_urls: true

file_length:
  warning: 500
  error: 1000

function_body_length:
  warning: 60
  error: 100

type_body_length:
  warning: 300
  error: 500

# Naming conventions
identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - i
    - j
    - x
    - y
    - z
    - a
    - e
    - v
    - M

# Force try should be allowed in tests
force_try:
  severity: warning

# Type name configuration
type_name:
  min_length:
    warning: 3
    error: 2
  max_length:
    warning: 50
    error: 60

# Reporting
reporter: "xcode"
