//
//  GravityModel.swift
//  Ephemeris
//
//  Earth gravity constants used by the SGP4/SDP4 propagator.
//

import Foundation

/// Earth gravity constants for SGP4/SDP4.
///
/// TLEs are generated by fitting observations with SGP4 using the **WGS-72** constants,
/// so `.wgs72` is the correct choice for propagating published element sets. Using
/// different constants than the ones the TLE was fitted with makes predictions worse,
/// not better, even though WGS-84 is the more modern Earth model.
///
/// Distances inside SGP4 are measured in Earth radii and time in minutes, which is why
/// the model carries `xke` (√μ in those units) alongside the familiar SI-style values.
///
/// ## Example
/// ```swift
/// let propagator = try SGP4(tle: tle, gravity: .wgs72)
/// ```
///
/// - Note: Reference: Vallado, Crawford, Hujsak, Kelso, "Revisiting Spacetrack Report #3",
///         AIAA 2006-6753, Section "Gravitational Constants".
public struct GravityModel: Equatable, Sendable {

    // MARK: - Properties

    /// Gravitational parameter μ (km³/s²)
    public let mu: Double

    /// Equatorial radius of the Earth (km)
    public let radiusEarthKm: Double

    /// √(μ) in units of Earth radii³ / minutes² (the "ke" constant of SGP4)
    public let xke: Double

    /// Minutes per SGP4 time unit (1 / xke)
    public let tumin: Double

    /// Second zonal harmonic (oblateness)
    public let j2: Double

    /// Third zonal harmonic (pear shape)
    public let j3: Double

    /// Fourth zonal harmonic
    public let j4: Double

    /// Ratio j3 / j2
    public let j3oj2: Double

    // MARK: - Standard Models

    /// WGS-72 constants. Use these for TLEs from CelesTrak and Space-Track.
    public static let wgs72 = GravityModel(mu: 398600.8, radiusEarthKm: 6378.135,
                                           j2: 0.001082616, j3: -0.00000253881, j4: -0.00000165597)

    /// WGS-72 with the rounded `xke` used by the original 1980 Spacetrack Report #3 code.
    /// Only useful for reproducing legacy results.
    public static let wgs72old = GravityModel(mu: 398600.79964, radiusEarthKm: 6378.135, xke: 0.0743669161,
                                              j2: 0.001082616, j3: -0.00000253881, j4: -0.00000165597)

    /// WGS-84 constants. Provided for completeness; TLEs are not fitted with these.
    public static let wgs84 = GravityModel(mu: 398600.5, radiusEarthKm: 6378.137,
                                           j2: 0.00108262998905, j3: -0.00000253215306, j4: -0.00000161098761)

    // MARK: - Initialization

    /// Creates a gravity model, deriving `xke` from μ and the Earth radius unless given.
    ///
    /// - Parameters:
    ///   - mu: Gravitational parameter (km³/s²)
    ///   - radiusEarthKm: Equatorial radius (km)
    ///   - xke: Optional explicit value for √μ in Earth radii and minutes
    ///   - j2: Second zonal harmonic
    ///   - j3: Third zonal harmonic
    ///   - j4: Fourth zonal harmonic
    public init(mu: Double, radiusEarthKm: Double, xke: Double? = nil, j2: Double, j3: Double, j4: Double) {
        self.mu = mu
        self.radiusEarthKm = radiusEarthKm
        // xke = 60 / sqrt(R³ / μ): converts μ to Earth radii and minutes
        let derivedXke = xke ?? 60.0 / sqrt(radiusEarthKm * radiusEarthKm * radiusEarthKm / mu)
        self.xke = derivedXke
        self.tumin = 1.0 / derivedXke
        self.j2 = j2
        self.j3 = j3
        self.j4 = j4
        self.j3oj2 = j3 / j2
    }
}
